sudo: required
services:
  - docker

before_install:
  - docker build -t agencyzero/<PROJECT_NAME> -f ./_deploy/client/dev.Dockerfile .

script:
  - docker run agencyzero/<PROJECT_NAME> npm run test:coverage