version: '3.1'
services:
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: client
    environment:
      NODE_ENV: production
    ports:
      - 90:3000
    restart: always # on-failure maybe used for a worker
  proxy:
    build: 
      context: .
      dockerfile: proxy.Dockerfile
    container_name: proxy
    ports:
      - 80:90
      - 443:90
    volumes:
      - ./_deploy/proxy/nginx.conf:/etc/nginx/conf.d/<PROJECT_NAME>.conf
      # - /etc/nginx/psw:/etc/nginx/psw
      # - /etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - client
    restart: always
  # server:
  #     image: node:alpine
  #   # command:
  #   container_name: server
# volumes: #optional
# networks: #optional