version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./_nginx
    ports:
      - '3001:80'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /node_modules
      - .:/client
  # api:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./api
  #   volumes:
  #     - /app/node_modules
  #     - ./api:/api
  # worker:



# version: '3'
# services:
#   dev:
#     build:
#       context: ./_deploy/client
#       dockerfile: dev.Dockerfile
#     environment:
#       NODE_ENV: development
#     ports:
#       - '3000:3000'
#     volumes:
#         - /client/node_modules
#         - .:/client
#     restart: always # on-failure maybe used for a worker
#   static:
#     build:
#       context: ./_deploy/client/static
#       dockerfile: Dockerfile
#     environment:
#       NODE_ENV: production
#     restart: always
#   # prod:
#   #   dev:
#   #   build:
#   #     context: ./_deploy/client
#   #     dockerfile: Dockerfile
#   #   environment:
#   #     NODE_ENV: development
#   #   ports:
#   #     - '90:3000'
#   #   volumes:
#   #       - /xxx_project_name_xxx/node_modules
#   #       - .:/xxx_project_name_xxx
#   #   restart: always # on-failure maybe used for a worker
#   test:
#     build:
#       context: ./_deploy/client
#       dockerfile: dev.Dockerfile
#     environment:
#       NODE_ENV: test
#     volumes:
#         - /xxx_project_name_xxx/node_modules
#         - .:/xxx_project_name_xxx
#     command: ["npm", "run", "test:watch"]
#     restart: always
#   # proxy: