version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./__nginx
    ports:
      - '90:80'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /node_modules
      - .:/client
    # comment out ports if using nginx:
    # ports: 
    #   - '95:3000'
  # api:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./api
  #   volumes:
  #     - /app/node_modules
  #     - ./api:/api
  # worker:
