version: '3.1'
services: # container. same as docker run
  client: # a friendly name, also DNS name inside network
    image: node:alpine # optional if you use build
    # command: # optional, replace default CMD specified by img
    container_name: client
    environment: # optional, same as -e in docker run
      NODE_ENV: production
    ports:
      - 80:3000
    # volumes: # optional, same as -v in docker run
    build:
      context: ./_deployment/_client
      dockerfile: client.Dockerfile
    working_dir: /$HOME/$PROJECT_NAME
    restart: always
  # server:
  #     image: node:alpine # optional if you use build
  #   # command: # optional, replace default CMD specified by img
  #   container_name: server
  http-proxy:
    image: nginx
    build: 
      context: ./_deployment/proxy
      dockerfile: nginx.Dockerfile
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./_deployment/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      # - /etc/nginx/psw:/etc/nginx/psw
      # - /etc/nginx/ssl:/etc/nginx/ssl
    # depends_on:
    #   - client
    # environment:
    #   - DOMAIN_NAME=$PROJECT_NAME.com
# volumes: #optional
# networks: #optional