# DEV dockerfile
version: '3'
services:
  client-dev:
    build:
      context: ./_deploy/client
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - '90:3000'
    volumes:
        - /<PROJECT_NAME>/node_modules
        - .:/<PROJECT_NAME>
    restart: always # on-failure maybe used for a worker
  test:
    build:
      context: ./_deploy/client
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - '90:3000'
    volumes:
        - /<PROJECT_NAME>/node_modules
        - .:/<PROJECT_NAME>
    command: ["npm", "run", "test:watch"]
    restart: always