version: '3.1'

services:

  production-nginx-container:
    container_name: 'production-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/xxx_project_name_xxx.conf
      - ./production-site:/xxx_project_name_xxx
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/xxx_project_name_xxx.com/fullchain.pem:/etc/letsencrypt/live/xxx_project_name_xxx.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/xxx_project_name_xxx.com/privkey.pem:/etc/letsencrypt/live/xxx_project_name_xxx.com/privkey.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge